language: node_js

node_js:
  - 0.6
  - 0.8

services:
  - cassandra

before_script:
  - sleep 5
  - 'CASSANDRA_CONF=/etc/cassandra /usr/local/cassandra/bin/nodetool status'

script: 
  - npm run-script lint
  - npm run-script test

notifications:
  email:
    - tomaz+travisci@tomaz.me
